"""StrategySpec v2 — hierarchical strategy IR with expression AST."""

from .ast_nodes import (
    ExprNode,
    ConstExpr,
    FeatureExpr,
    StateVarExpr,
    PositionAttrExpr,
    ComparisonExpr,
    AllExpr,
    AnyExpr,
    NotExpr,
    CrossExpr,
    LagExpr,
    RollingExpr,
    PersistExpr,
    expr_from_dict,
)
from .schema_v2 import (
    EntryPolicyV2,
    ExitActionV2,
    ExitRuleV2,
    ExitPolicyV2,
    PositionSizingV2,
    RiskDegradationActionV2,
    RiskDegradationRuleV2,
    RiskPolicyV2,
    PreconditionV2,
    RegimeV2,
    ExecutionAdaptationOverrideV2,
    ExecutionAdaptationRuleV2,
    ExecutionPolicyV2,
    StateUpdateV2,
    StateEventV2,
    StateGuardV2,
    StatePolicyV2,
    StrategySpecV2,
)
